import "./globals.css";
import {AntdRegistry} from '@ant-design/nextjs-registry';
// 全局汉化antd
import {ConfigProvider} from 'antd';
import zhCN from 'antd/locale/zh_CN';


export const metadata = {
    title: "Create Next App", description: "Generated by create next app",
};

const RootLayout = ({children}) => (
    <html lang="zh">
    <head>
        <meta charSet="utf-8"/>
        <meta name="keywords" content="WatchMe，WatchMeUser"/>
        <meta name="description" content="服务器监控软件"/>
        <meta name="author" content="PushMe"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>WatchMe</title>
    </head>
    {/*<body className={inter.className}>*/}
    <body>
    <AntdRegistry>
        <ConfigProvider locale={zhCN}>
            {children}
        </ConfigProvider>
    </AntdRegistry>
    </body>
    </html>
);

export default RootLayout;
